### ISSUE TITLE
Remark that it only officially supports RAM-style plots

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semptools#118]
# To-Dos

- [x] Enumerate functions that do not work with the LISREL-style representation.
- [x] `set_cfa_layout()`: Fixed (74a055751ebdd7e6aaddfaf62f6d7975f6b37ec0)
- [x] Enumerate functions that do work with the LISREL-style representation.
- [x] `change_node_label()`
- [x] `keep_nodes()`
- [x] `drop_nodes()`
- [x] `layout_matrix()`
- [x] `set_curve()`
- [x] `set_sem_layout()`

# Status

Working in the branch `check_ram_lisrel`.

Only `set_cfa_layout()` need to check whether the  graph of LISREL-style and acts accordingly.

# Note

*Some* functions do work with LISREL-style plots. Check.

**Comment by sfcheung** [comment]
Fixed in #127
