### ISSUE TITLE
Reusing pipes

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semptools#145]
# To-Dos

- [ ] Revise functions such that they will skip edges or nodes not found.
- [ ] See if we can store the fit object into the igraph object.
- [ ] Write an articles to illustrate how to reuse pipes.

# Status

On hold. For the next release.
