### ISSUE TITLE
Review where we are and plan ahead

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semptools#60]
# To-Do
- [X] Review those changes and push them to the devel branch. <- No need to do this. Will focus on the most urgent milestone (https://github.com/sfcheung/semptools/milestone/3)
- [x] Review all existing changes and issues. <- Prepared a document to summarize the issues. Changes will be reviewed while working on the most urgent milestone (https://github.com/sfcheung/semptools/milestone/3).
- [x] Set a few milestones to prioritize changes to be made. <- No need to do this. Will focus on the most urgent milestone (https://github.com/sfcheung/semptools/milestone/3)
