### ISSUE TITLE
Introduce all new functions for v0.2.9 (and those few in v0.2.8.1 not yet introduced)

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semptools#66]
# To-Do

- [ ] Describe `change_node_label` (added in v0.2.8.1) in vignettes.
- [ ] Describe how to use named vector (an option added in v0.2.8.1) in vignettes.
- [ ] (To-Add) Describe other new functions to be added in v0.2.9
