### ISSUE TITLE
Finalize the release of v0.2.9

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semptools#68]
Final checks before pushing v0.2.9 (work on this branch: `devel_final_check`

# To-Do

- [x] Check the documentation of new functions.
- [x] Check the documentation of old functions. Include named vectors in the documentation of affected functions.
- [x] Proofread the vignettes.
- [x] Update NEWS.
- [x] Update DESCRIPTION.
- [x] Test by `testthat`.
- [x] Check by `devtools::check`.
