### ISSUE TITLE
Update the vignettes to use native forward pipe operator `|>` instead of `%>%` in `magrittr`

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semptools#71]
# Status
Done in version 0.2.9.

# To-Do
- [x] Revise the vignettes and other documentation files to replace `%>%` by the native forward pipe operator `|>`, introduced in R 4.1.0. Will remark the `%>%` can be used in older version of R.
- [x] Replace `%>%` by `|>` in all files
- [x] Remove `magrittr` from depends.
