### ISSUE TITLE
Update `change_node_label` to allow changing options related to drawing the labels

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semptools#72]
# Note
When a label is changed, the original option such as font size may no longer be appropriate and needs to be changed. However, this can be done when a graph is first generated by `semPlot::semPaths` because the labels are not specified in this step. Using `qgraph::qgraph` again is not an option because it will change rebuild the graph and override changes made by `semptools` functions.

Address this issue in the branch `update_change_node_label`.

# To-Do
- [x] Revise `change_node_label` to allow modifying `graphAttributes$Nodes$label.cex`.
- [x] Revise `change_node_label` to allow modifying `plotOptions$label.scale`.
- [x] Revise `change_node_label` to allow modifying `plotOptions$label.prop`.
- [x] Revise `change_node_label` to allow modifying `plotOptions$label.norm`.
