### ISSUE TITLE
Helper functions to make it easier to assign indicators to factors and set the orders of indicators

### ISSUE THREAD

**Issue by sfcheung** [sfcheung/semptools#90]
# To-Dos
- [x] ~Write `auto_indicator_config()`. It returns a named vector of he indicator order, names being the factor names.~
- [x] ~Modify `set_sem_layout()` and `set_cfa_layou()`: If either `indicator_order` or `indicator_factor` is not set, or both are not set, it will check whether (a) a `lavaan` model syntax is supplied, or (b) a `lavaan-class` object is supplied. If yes, it will adopt the appropriate option.~!
- [x] Finalize `auto_indicator_order()`.
- [x] Finalize `add_object()`, for future use.
- [x] Finalize `lavaan_indicator_order()`.
- [x] Finalize changes in `set_cfa_layout()`.
- [x] Finalize changes in `set_sem_layout()`.

# Status

Work in `layout_helpers`.

# What have been done

- A function to automatically determine the order based on the semPaths() output. The set_*_layout functions will use this function if indicator_order is not supplied.
- The set_*_layout functions also accept a named vector for indicator_order. The names will be used for indicator_factor.
- A function to convert a lavan model syntax order.

# Option 1 (Not used)

In `set_sem_layout` and `set_cfa_layout`, users need to supply a character vector to match indicators to factors and set the orders. This can be improved by writing a helper function to generate the two vectors. E.g.,

```
x <- 
"
f2 =~ x1 + x3 + x4
f1 =~ x5 + x7 + x6
"
```

The function should generate these two vectors:

```
a1 <- c(""x1", "x3", "x4", "x5", "x7", "x6")
a2  <- c("f2", "f2", "f2", "f1", "f1", "f1")
```

Because users of `semptools` are also users of `lavaan`, it is easier for them to use syntax similar to that of `lavaan`.

# Option 2 (Not used)

We used vectors as the input because the output of `semPlot::semPaths()` does not store the output of `lavaan`. However, we already have functions (e.g., `mark_sig()`) that asks for the output of `lavaan`.

Therefore, instead of asking users to specify the syntax again,  we can just write simple helper functions to generate the vectors, instead of asking users to do the following:

```r
indicator_order  <- c("x04", "x05", "x06", "x07",
                      "x01", "x02", "x03",
                      "x11", "x12", "x13", "x14",
                      "x08", "x09", "x10")
indicator_factor <- c( "f2",  "f2",  "f2",  "f2",
                       "f1",  "f1",  "f1",
                       "f4",  "f4",  "f4",  "f4",
                       "f3",  "f3",  "f3")
```

we can write two helpers to do this:

```r
auto_indicator_order(fit)
auto_indicator_factor(fit)
```

These functions will inspect the parameter table and then generate these two vectors automatically.

**Comment by sfcheung** [comment]
Done in #136
